# Generated by Django 4.2.30 on 2026-04-15 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('loyalty_status', models.CharField(choices=[('None', 'None'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Elite', 'Elite')], default='None', max_length=20)),
                ('loyalty_tier', models.CharField(blank=True, max_length=20)),
                ('points_balance', models.PositiveIntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite'), ('Presidential', 'Presidential')], default='Standard', max_length=20)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size_sqm', models.PositiveIntegerField(default=30)),
                ('bed_type', models.CharField(choices=[('Single Bed', 'Single Bed'), ('Double Bed', 'Double Bed'), ('King Bed', 'King Bed'), ('Queen Bed', 'Queen Bed'), ('Twin Beds', 'Twin Beds')], default='King Bed', max_length=20)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=20, unique=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('num_adults', models.PositiveIntegerField(default=1)),
                ('num_children', models.PositiveIntegerField(default=0)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Checked-In', 'Checked-In'), ('Checked-Out', 'Checked-Out'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('complimentary_breakfast', models.BooleanField(default=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('gym_pool_access', models.BooleanField(default=False)),
                ('transportation', models.CharField(blank=True, max_length=100)),
                ('extras_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('city_tax', models.DecimalField(decimal_places=2, default=49.5, max_digits=8)),
                ('billing_notes', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotel.guest')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='hotel.room')),
            ],
        ),
    ]
